arch:
  - amd64
  - ppc64le
language: cpp
dist: trusty
install:
  - sudo apt-get install lcov
  - gem install coveralls-lcov
  - sudo apt-get install libopencv-dev
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - cmake --build .
  - ctest -V
after_success:
  - lcov -d . -c -o coverage.info
  - lcov -r coverage.info "/usr*" "$(readlink -f ../test)/*" -o coverage.info
  - lcov -l coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
